; Listing generated by Microsoft (R) Optimizing Compiler Version 19.14.26430.0 

	TITLE	C:\Users\caissa\source\repos\[Section 2] Template Basic\[Section 2] Template Basic\template alias.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	_main
EXTRN	@_RTC_CheckStackVars@8:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\caissa\source\repos\[section 2] template basic\[section 2] template basic\template alias.cpp
;	COMDAT _main
_TEXT	SEGMENT
_main	PROC						; COMDAT

; 29   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 248				; 000000f8H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-248]
	mov	ecx, 62					; 0000003eH
	mov	eax, -858993460				; ccccccccH
	rep stosd

; 30   : 	//DWORD n;
; 31   : 	//F f;
; 32   : 
; 33   : 	Point<int, double> p;
; 34   : 
; 35   : 	Point2<int> p2;
; 36   : 	Point3<int> p3;
; 37   : }

	xor	eax, eax
	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN7@main
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
$LN7@main:
	DD	3
	DD	$LN6@main
$LN6@main:
	DD	-20					; ffffffecH
	DD	16					; 00000010H
	DD	$LN3@main
	DD	-36					; ffffffdcH
	DD	8
	DD	$LN4@main
	DD	-52					; ffffffccH
	DD	8
	DD	$LN5@main
$LN5@main:
	DB	112					; 00000070H
	DB	51					; 00000033H
	DB	0
$LN4@main:
	DB	112					; 00000070H
	DB	50					; 00000032H
	DB	0
$LN3@main:
	DB	112					; 00000070H
	DB	0
_main	ENDP
_TEXT	ENDS
END
