; Listing generated by Microsoft (R) Optimizing Compiler Version 19.14.26430.0 

	TITLE	C:\Users\caissa\source\repos\[Section 2] Template Basic\[Section 2] Template Basic\10 template alias.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

END
